
services:
# ======================
# Nats-Server
# ====================== 
  nats-server:
    image: nats:latest

# ======================
# Client Gateway
# ====================== 
  client-gateway:
    image: us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/client-gateway
    container_name: client-gateway-container
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT= ${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVER}  

# ======================
# Auth Microservice
# ======================
  auth-ms:
    image: us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/auth-ms
    container_name: auth-ms-container
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=${AUTH_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

# ======================
# Products Microservice
# ======================
  products-ms:
    image: us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/products-ms
    container_name: products-ms-container
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - DATABASE_URL=${PRODUCTS_DB_URL}

# ======================
# Orders Microservice
# ====================== 
  orders-ms:
    image: us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/orders-ms
    container_name: orders-ms-container
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DB_URL}
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - DATABASE_URL=${ORDERS_DB_URL}

# ======================
# Payments Microservice
# ======================
  payments-ms:
    image: us-east4-docker.pkg.dev/ecommerce-microserivces/nestjs-ecommerce-registry/payments-ms
    container_name: payments-ms-container
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
