
services:
# ======================
# Nats-Server
# ====================== 
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

# ======================
# Client Gateway
# ====================== 
  client-gateway:
    container_name: client-gateway
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    develop:
      watch:
        # Sincroniza cambios en los archivos de código fuente
        - action: sync
          path: ./client-gateway/src
          target: /usr/src/app/src
          ignore:
            - node_modules/  # Ignora la carpeta node_modules
            - dist/          # Ignora archivos compilados

        # Reconstruye la imagen si cambia package.json
        - action: rebuild
          path: ./client-gateway/package.json
    command: bun start:dev
    environment:
      - PORT= ${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=n${NATS_SERVER}

# ======================
# Products Microservice
# ======================
  products-ms:
    container_name: products-ms
    build: ./products-ms
    develop:
      watch:
        - action: sync
          path: ./products-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./products-ms/package.json
    command: bun start:dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - DATABASE_URL=${PRODUCTS_DB_URL}

# ======================
# Orders Microservice
# ====================== 
  orders-ms:
    container_name: orders-ms
    depends_on:
      - orders-db
    build: ./orders-ms
    develop:
      watch:
        - action: sync
          path: ./orders-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./orders-ms/package.json
    command: bun start:dev
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - DATABASE_URL=${ORDERS_DB_URL}
      
      
      
   
  # Orders-db   
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

# ======================
# Payments Microservice
# ======================
  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    develop:
      watch:
        - action: sync
          path: ./payments-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./payments-ms/package.json
    command: bun start:dev
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
